version: '3.9'
services:
  api:
    build:
      context: ./api
    image: code-executor-api:dev
    environment:
      PORT: 8080
      API_KEYS: dev_123:dev:5:10
      SIGNING_KEY: local-signing-key
      SANDBOX_WORKDIR: /sandbox
      STORAGE_DIR: /data/storage
      PUBLIC_BASE_URL: http://localhost:8080
      SECCOMP_PROFILE: /seccomp/default.json
      HOST_SANDBOX_DIR: ${HOST_SANDBOX_DIR:-${PWD}/sandbox}
      # Optional: explicitly set admin UI path (auto-detected if not set)
      # ADMIN_UI_PATH: /app/web/admin
      # APPARMOR_PROFILE disabled on macOS Docker Desktop
      # APPARMOR_PROFILE: codeexecutor
      RUNNER_IMAGE_PYTHON: code-executor-runner-python:dev
      RUNNER_IMAGE_NODE: code-executor-runner-node:dev
      RUNNER_IMAGE_RUBY: code-executor-runner-ruby:dev
      RUNNER_IMAGE_PHP: code-executor-runner-php:dev
      RUNNER_IMAGE_GO: code-executor-runner-go:dev
      DISABLE_SANDBOX_SECURITY: '1'
    ports:
      - '8080:8080'
    volumes:
      - ./seccomp:/seccomp:ro
      - ./apparmor:/apparmor:ro
      - ./web/admin:/app/web/admin:ro
      - ./sandbox:/sandbox
      - ./artifacts:/data/storage
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - runner-python
      - runner-node
      - runner-ruby
      - runner-php
      - runner-go
  runner-python:
    build: ./runners/python
    image: code-executor-runner-python:dev
    profiles: ['runners']
    command: ["sleep", "infinity"]
  runner-node:
    build: ./runners/node
    image: code-executor-runner-node:dev
    profiles: ['runners']
    command: ["sleep", "infinity"]
  runner-ruby:
    build: ./runners/ruby
    image: code-executor-runner-ruby:dev
    profiles: ['runners']
    command: ["sleep", "infinity"]
  runner-php:
    build: ./runners/php
    image: code-executor-runner-php:dev
    profiles: ['runners']
    command: ["sleep", "infinity"]
  runner-go:
    build: ./runners/go
    image: code-executor-runner-go:dev
    profiles: ['runners']
    command: ["sleep", "infinity"]
